// Copyright 2026 Oliver Mee and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newIconsGetCmd(flags *rootFlags) *cobra.Command {
	var flagColor string
	var flagWidth string
	var flagHeight string
	var flagFlip string
	var flagRotate string
	var flagBox bool

	cmd := &cobra.Command{
		Use:         "get <prefix> <name>",
		Short:       "Fetch one icon as SVG, optionally recoloured and resized",
		Example:     "  iconify icons get lucide arrow-right --color '#404041' --width 32",
		Annotations: map[string]string{"pp:endpoint": "icons.get", "pp:method": "GET", "pp:path": "/{prefix}/{name}.svg", "mcp:read-only": "true", "pp:happy-args": "prefix=lucide;name=home"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <prefix> <name>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <prefix> <name>"))
			}
			if cmd.Flags().Changed("flip") {
				allowedFlip := []string{"horizontal", "vertical", "horizontal,vertical"}
				validFlip := false
				for _, v := range allowedFlip {
					if flagFlip == v {
						validFlip = true
						break
					}
				}
				if !validFlip {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagFlip, "flip", allowedFlip)
				}
			}
			if cmd.Flags().Changed("rotate") {
				allowedRotate := []string{"90", "180", "270"}
				validRotate := false
				for _, v := range allowedRotate {
					if flagRotate == v {
						validRotate = true
						break
					}
				}
				if !validRotate {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagRotate, "rotate", allowedRotate)
				}
			}
			path := "/{prefix}/{name}.svg"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("prefix is required\nUsage: %s <%s>", cmd.CommandPath(), "prefix"))
			}
			path = replacePathParam(path, "prefix", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("name is required\nUsage: %s <%s>", cmd.CommandPath(), "name"))
			}
			path = replacePathParam(path, "name", args[1])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			headerOverrides := map[string]string{
				"X-Printing-Press-Binary-Response": "true",
			}

			params := map[string]string{}
			if flagColor != "" {
				params["color"] = formatCLIParamValue(flagColor)
			}
			if flagWidth != "" {
				params["width"] = formatCLIParamValue(flagWidth)
			}
			if flagHeight != "" {
				params["height"] = formatCLIParamValue(flagHeight)
			}
			if flagFlip != "" {
				params["flip"] = formatCLIParamValue(flagFlip)
			}
			if flagRotate != "" {
				params["rotate"] = formatCLIParamValue(flagRotate)
			}
			if flagBox != false {
				params["box"] = formatCLIParamValue(flagBox)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "icons", false, path, params, headerOverrides, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}
	cmd.Flags().StringVar(&flagColor, "color", "", "Replace currentColor with a fixed colour, e.g. '#404041'")
	cmd.Flags().StringVar(&flagWidth, "width", "", "Width. Setting only one dimension scales the other to match")
	cmd.Flags().StringVar(&flagHeight, "height", "", "Height. Setting only one dimension scales the other to match")
	cmd.Flags().StringVar(&flagFlip, "flip", "", "Flip the icon: horizontal, vertical, or both (one of: horizontal, vertical, horizontal,vertical)")
	cmd.Flags().StringVar(&flagRotate, "rotate", "", "Rotate by 90, 180, or 270 degrees (one of: 90, 180, 270)")
	cmd.Flags().BoolVar(&flagBox, "box", false, "Add an empty rectangle matching the viewBox")

	return cmd
}
