// Copyright 2026 Oliver Mee and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newIconsCssCmd(flags *rootFlags) *cobra.Command {
	var flagIcons string

	cmd := &cobra.Command{
		Use:         "css <prefix>",
		Short:       "Generate a CSS mask sprite for a list of icons from one set",
		Example:     "  iconify icons css lucide --icons home,star > icons.css",
		Annotations: map[string]string{"pp:endpoint": "icons.css", "pp:method": "GET", "pp:path": "/{prefix}.css", "mcp:read-only": "true", "pp:happy-args": "prefix=lucide;--icons=home,star"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <prefix>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <prefix>"))
			}
			if !cmd.Flags().Changed("icons") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "icons")
			}
			path := "/{prefix}.css"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("prefix is required\nUsage: %s <%s>", cmd.CommandPath(), "prefix"))
			}
			path = replacePathParam(path, "prefix", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			headerOverrides := map[string]string{
				"X-Printing-Press-Binary-Response": "true",
			}

			params := map[string]string{}
			if flagIcons != "" {
				params["icons"] = formatCLIParamValue(flagIcons)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "icons", false, path, params, headerOverrides, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}
	cmd.Flags().StringVar(&flagIcons, "icons", "", "Comma separated icon names")

	return cmd
}
