// Copyright 2026 Oliver Mee and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIconsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "icons",
		Short:       "Search and fetch individual icons",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIconsCssCmd(flags))
	cmd.AddCommand(newIconsDataCmd(flags))
	cmd.AddCommand(newIconsGetCmd(flags))
	cmd.AddCommand(newIconsSearchCmd(flags))
	return cmd
}
