// Copyright 2026 Oliver Mee and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMetaVersionCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "version",
		Short:       "Report the Iconify API version and serving region",
		Example:     "  iconify-pp-cli meta version",
		Annotations: map[string]string{"pp:endpoint": "meta.version", "pp:method": "GET", "pp:path": "/version", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/version"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			headerOverrides := map[string]string{
				"X-Printing-Press-Binary-Response": "true",
			}

			params := map[string]string{}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "meta", false, path, params, headerOverrides, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}

	return cmd
}
