// Copyright 2026 Oliver Mee and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSetsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sets",
		Short:       "Browse and inspect icon sets",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSetsGetCmd(flags))
	cmd.AddCommand(newSetsListCmd(flags))
	return cmd
}
